'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {buildLifeAreas}=require('../utils/kundliLifeAreas');
const {KUNDLI_INTERPRETATION_RULESET,KUNDLI_INTERPRETATION_VERSION,SUPPORTED_AREAS,buildKundliInterpretation,withKundliInterpretation}=require('../utils/kundliInterpretation');
function canonical({careerSign='Karka',careerLord='Moon',careerOccupants=['Jupiter'],careerAspect='Jupiter',certainty='EXACT'}={}){const signs=['Mesha','Vrishabha','Mithuna','Karka','Simha','Kanya','Tula','Vrischika','Dhanu',careerSign,'Kumbha','Meena'],lords=['Mars','Venus','Mercury','Moon','Sun','Mercury','Venus','Mars','Jupiter',careerLord,'Saturn','Jupiter'];const names=['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn','Rahu','Ketu'];const planets=names.map((name,i)=>({name,sign:signs[i],house:i+1,house_status:'AVAILABLE',status:'AVAILABLE',source:'PROVIDER'}));const normalized={birth_time_certainty:certainty,houses:{status:'AVAILABLE',method:'WHOLE_SIGN_FROM_PROVIDER_SIDEREAL_SIGNS_V1',items:signs.map((sign,i)=>({number:i+1,sign,lord:lords[i],occupants:i===9?careerOccupants:[],source:'DERIVED',method:'WHOLE_SIGN_FROM_PROVIDER_SIDEREAL_SIGNS_V1',status:'AVAILABLE'}))},planets,aspects:{status:'AVAILABLE',items:[{source_planet:careerAspect,target_house:10,target_sign:careerSign,method:'PARASHARI_GRAHA_DRISHTI_V1'}]},structural_conditions:{status:'AVAILABLE',items:planets.map(p=>({planet:p.name,conditions:[],status:'AVAILABLE',source:'DERIVED'}))},dasha:{status:'UNAVAILABLE'},charts:{d9:{status:'UNAVAILABLE'},bhava:{status:'UNAVAILABLE'}},yogas:[],doshas:[]};normalized.life_areas=buildLifeAreas(normalized);return normalized;}
function interpretation(options){const input=canonical(options);return buildKundliInterpretation(input,{birth_time_certainty:options?.certainty||'EXACT'});}

test('K4.1 is deterministic, versioned and leaves K3 unchanged',()=>{const input=canonical(),before=structuredClone(input.life_areas),a=buildKundliInterpretation(input,{birth_time_certainty:'EXACT'}),b=buildKundliInterpretation(input,{birth_time_certainty:'EXACT'});assert.equal(KUNDLI_INTERPRETATION_RULESET,'KUNDLI_INTERPRETATION_RULESET_V2');assert.equal(KUNDLI_INTERPRETATION_VERSION,'kundli-k4.1-interpretation-v1');assert.deepEqual(a,b);assert.deepEqual(input.life_areas,before);assert.deepEqual(Object.keys(a.areas),SUPPORTED_AREAS);assert.equal(a.status,'AVAILABLE');});

test('Career applies role-aware evidence and produces consumer meaning',()=>{const career=interpretation().areas.CAREER;assert.equal(career.status,'AVAILABLE');assert.match(career.summary.en,/work style and responsibilities/);assert.match(career.summary.en,/responsive|support|knowledge|advisory/i);assert.ok(career.directions.some(x=>x.role==='HOUSE_LORD'&&x.planet==='Moon'));assert.ok(career.evidence.some(x=>x.type==='HOUSE_STRUCTURE'&&x.occupants.includes('Jupiter')));assert.ok(career.evidence.some(x=>x.type==='HOUSE_RECEIVES_DRISHTI'&&x.planet==='Jupiter'));assert.ok(career.directions.some(x=>x.role==='LORD_PLACEMENT'));assert.match(career.evidenceSummary.en,/House 10: Karka.*Lord: Moon.*Jupiter/);assert.ok(career.strengths.length>=1);assert.ok(career.challenges.length>=1);assert.match(career.deepDivePrompt.en,/career patterns/i);});

test('materially different Career evidence selects different directions and summary',()=>{const lunar=interpretation().areas.CAREER;const saturn=interpretation({careerSign:'Makara',careerLord:'Saturn',careerOccupants:['Mercury'],careerAspect:'Mars'}).areas.CAREER;assert.notEqual(lunar.summary.en,saturn.summary.en);assert.notDeepEqual(lunar.directions.map(x=>x.label.en),saturn.directions.map(x=>x.label.en));assert.match(lunar.summary.en,/responsive|support/i);assert.match(saturn.summary.en,/structured|communication|analysis|organization/i);assert.match(saturn.evidenceSummary.en,/Makara.*Saturn.*Mercury.*Mars/);});

test('all areas are useful, distinct, bilingual and contextual',()=>{const result=interpretation(),summaries=new Set(),prompts=new Set();for(const id of SUPPORTED_AREAS){const area=result.areas[id];assert.equal(area.status,'AVAILABLE',id);assert.ok(area.summary.en.split(/[.!?]/).filter(Boolean).length>=2,id);assert.ok(area.summary.hi.length>30,id);assert.ok(area.directions.length>=2,id);assert.ok(area.strengths.length>=1,id);assert.ok(area.evidenceSummary.en,id);assert.ok(area.deepDivePrompt.en,id);summaries.add(area.summary.en);prompts.add(area.deepDivePrompt.en);}assert.equal(summaries.size,8);assert.equal(prompts.size,8);assert.notEqual(result.areas.CAREER.summary.en,result.areas.MARRIAGE.summary.en);assert.match(result.areas.EDUCATION.summary.en,/learning style/i);assert.match(result.areas.FINANCE.summary.en,/resource-building/i);assert.match(result.areas.PERSONALITY.summary.en,/temperament/i);assert.match(result.areas.PROPERTY.summary.en,/home, family/i);assert.match(result.areas.SPIRITUALITY.summary.en,/reflection, meaning/i);});

test('health stays non-medical and unsupported predictions are absent',()=>{const result=interpretation(),health=result.areas.HEALTH,serialized=JSON.stringify(result);assert.match(health.summary.en,/routine, workload and balance/i);assert.match(health.disclaimer.en,/not medical advice or diagnosis/i);assert.doesNotMatch(health.summary.en,/disease|diagnos|treatment|illness|risk/i);assert.doesNotMatch(serialized,/definitely|guaranteed success|guaranteed profession|salary|crore|marriage date|spouse name|divorce|lifespan|children count|remed(?:y|ies)|gemstone/i);assert.doesNotMatch(serialized,/mahadasha|antardasha|navamsha result|bhava chart result|manglik|mangal dosha|yoga detected/i);});

test('approximate time and insufficient evidence degrade safely',()=>{const approximate=interpretation({certainty:'APPROXIMATE'});assert.equal(approximate.birth_time_certainty,'APPROXIMATE');assert.ok(Object.values(approximate.areas).every(x=>x.limitations.includes('BIRTH_TIME_NOT_EXACT_TIME_SENSITIVE_FACTORS_MAY_VARY')));const weak=canonical();weak.life_areas={status:'READY',items:[{id:'CAREER',status:'READY',evidence:[]}]};assert.equal(buildKundliInterpretation(weak).areas.CAREER.status,'UNAVAILABLE');});

test('K4.1 remains pure and account enrichment makes no provider or AI call',()=>{const input=canonical(),attached=withKundliInterpretation(input,{birth_time_certainty:'EXACT'});assert.notEqual(attached,input);assert.equal(input.interpretation,undefined);assert.equal(attached.interpretation.version,KUNDLI_INTERPRETATION_VERSION);assert.doesNotMatch(buildKundliInterpretation.toString(),/fetch|axios|gemini|groq|openai|prokerala/i);const server=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8'),view=server.slice(server.indexOf('function accountJyotishView'),server.indexOf("app.get('/account/me'"));assert.match(view,/withKundliInterpretation/);assert.doesNotMatch(view,/fetchPrimaryKundli|fetchBasicKundli|gemini|groq/i);});
