#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path');
const {publicationIssues}=require('./mantra_publication');
const {sacredTextFindings}=require('./mantra_quality');
const ROOT=path.resolve(__dirname,'../data/mantra'),OUT=path.join(ROOT,'m5');
const LONG_FORM=new Set(['STOTRA','ASHTAKAM','KAVACHA','CHALISA','NAMAVALI','SAHASRANAMA']);
const JAPA_TYPES=new Set(['MANTRA','NAMA_JAPA','VEDIC_MANTRA','BIJA_MANTRA','GAYATRI_MANTRA','DHYANA_MANTRA','SHANTI_MANTRA']);
const key=v=>String(v||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'');
function truthfulType(row){const n=key(row.canonical_name);if(/sahasranama/.test(n))return'SAHASRANAMA';if(/ashtottara|shatashtanama|dvadasanama|namavali/.test(n))return'NAMAVALI';if(/ashtakam/.test(n))return'ASHTAKAM';if(/kavacha/.test(n))return'KAVACHA';if(/chalisa/.test(n))return'CHALISA';if(row.id==='gayatri')return'GAYATRI_MANTRA';if(/beej|bija/.test(key(row.canonical_name))&&row.content_type==='MANTRA')return'BIJA_MANTRA';return row.content_type;}
function aliasesOf(row){return [...new Set([...(row.alternate_names||[]),...Object.values(row.names||{}).filter(v=>typeof v==='string')])];}
function candidate(row){const contentType=truthfulType(row),longForm=LONG_FORM.has(contentType),japa=JAPA_TYPES.has(contentType)&&!longForm;
  const text=typeof row.sanskrit_text==='string'?row.sanskrit_text:null,trans=row.transliteration_iast||row.transliteration_simple||null;
  const result={canonical_id:row.id,canonical_name:row.canonical_name,alternate_names:aliasesOf(row),deity:(row.deity_ids||[])[0]||'Unspecified',deity_form:row.parent_deity_id||null,tradition:row.tradition||null,context:row.sampradaya||null,content_type:contentType,primary_classification:longForm?'LONG_FORM_RECITATION':contentType==='PRAYER'||contentType==='PRARTHANA'?'PRAYER':contentType==='SHLOKA'?'VERSE_RECITATION':'JAPA_PRACTICE',classifications:longForm?['RECITATION','LONG_FORM']:[japa?'JAPA':'RECITATION'],sanskrit_text:text,transliteration:trans,meaning:row.meanings||{hi:null,en:null},traditional_context:row.traditional_context||null,purpose_context_tags:(row.purpose_ids||[]).filter(v=>v&&v!=='UNSPECIFIED'),practice_level:row.practice_level||'GENERAL_DEVOTIONAL',requires_guru_guidance:row.requires_guru_guidance,advanced_practice_available:row.advanced_practice_available===true,japa_eligibility:japa?'ELIGIBLE_BY_CONTENT_TYPE':'NOT_JAPA_CONTENT',consumer_experience:longForm?'LONG_FORM_RECITATION':japa?'JAPA':'READING_RECITATION',text_sources:row.text_sources||[],transliteration_sources:row.transliteration_sources||[],meaning_sources:row.meaning_sources||[],practice_sources:row.practice_sources||[],pronunciation_sources:row.pronunciation_sources||[],audio_sources:row.audio_sources||[],text_verification:row.text_verification||'UNVERIFIED',transliteration_verification:row.transliteration_verification||'UNVERIFIED',meaning_verification:row.meaning_verification||'UNVERIFIED',practice_verification:row.practice_verification||'UNVERIFIED',pronunciation_verification:row.pronunciation_verification||'UNVERIFIED',audio_verification:row.audio_verification||'UNVERIFIED',rights_status:row.rights_status||'REVIEW_REQUIRED',rights_reference:row.rights_reference||null,review_status:row.publication_status||'REVIEW_REQUIRED',source_stage:row.source_stage||'REVIEW_REQUIRED'};
  const blockers=[];if(!text)blockers.push('SACRED_TEXT_REQUIRED');else blockers.push(...sacredTextFindings(text));if(!trans)blockers.push('TRANSLITERATION_REQUIRED');if(!result.text_sources.length)blockers.push('TEXT_SOURCE_REQUIRED');if(!result.transliteration_sources.length)blockers.push('TRANSLITERATION_SOURCE_REQUIRED');if(!result.meaning_sources.length)blockers.push('MEANING_SOURCE_REQUIRED');if(!result.practice_sources.length)blockers.push('PRACTICE_SOURCE_REQUIRED');if(!result.pronunciation_sources.length)blockers.push('PRONUNCIATION_SOURCE_REQUIRED');if(!result.audio_sources.length)blockers.push('AUDIO_SOURCE_REQUIRED');blockers.push(...publicationIssues({...row,id:row.id}));result.publication_blockers=[...new Set(blockers)];result.publication_eligibility=result.publication_blockers.length?'BLOCKED':'READY';return result;}
function build(rows){const items=rows.map(candidate),ids=new Set(),aliasOwners=new Map(),duplicates=[],aliasConflicts=[];for(const item of items){if(ids.has(item.canonical_id))duplicates.push(item.canonical_id);ids.add(item.canonical_id);for(const alias of [item.canonical_name,...item.alternate_names]){const k=key(alias),owner=aliasOwners.get(k);if(owner&&owner!==item.canonical_id)aliasConflicts.push({normalized_alias:k,canonical_ids:[owner,item.canonical_id]});else if(k)aliasOwners.set(k,item.canonical_id);}}
  for(const conflict of aliasConflicts)for(const id of conflict.canonical_ids){const item=items.find(x=>x.canonical_id===id);if(item&&!item.publication_blockers.includes('POTENTIAL_CANONICAL_DUPLICATE'))item.publication_blockers.push('POTENTIAL_CANONICAL_DUPLICATE');}
  const count=field=>items.filter(x=>x[field]).length,verified=field=>items.filter(x=>x[field]==='VERIFIED').length,breakdown=field=>items.reduce((a,x)=>{const v=x[field]||'Unspecified';a[v]=(a[v]||0)+1;return a;},{});
  return {items,duplicates,aliasConflicts,summary:{production_snapshot_count:29,total_candidates:items.length,distinct_candidates:ids.size-aliasConflicts.length,duplicate_ids:duplicates.length,alias_conflicts:aliasConflicts.length,with_sanskrit_text:count('sanskrit_text'),fully_text_sourced:items.filter(x=>x.text_sources.length&&x.text_verification==='VERIFIED').length,transliteration_present:count('transliteration'),transliteration_ready:verified('transliteration_verification'),meaning_ready:verified('meaning_verification'),practice_ready:verified('practice_verification'),pronunciation_ready:verified('pronunciation_verification'),audio_ready:verified('audio_verification'),rights_cleared:items.filter(x=>['PUBLIC_DOMAIN','LICENSED','PROJECT_OWNED','PERMISSION_GRANTED'].includes(x.rights_status)&&x.rights_reference).length,publication_ready:items.filter(x=>x.publication_eligibility==='READY').length,blocked:items.filter(x=>x.publication_eligibility==='BLOCKED').length,by_deity:breakdown('deity'),by_content_type:breakdown('content_type'),by_japa_eligibility:breakdown('japa_eligibility')}};}
function sourceRegistry(items){const refs=new Map();for(const item of items)for(const ref of item.source_references||[]){const url=ref.url;if(url&&!refs.has(url))refs.set(url,{source_id:`discovery-${refs.size+1}`,source_title:ref.name||'Discovery reference',work:item.canonical_name,edition:null,publisher:null,url,project_reference:null,rights_status:'REVIEW_REQUIRED',rights_reference:null,fields_supported:[],review_state:'REGISTERED',evidence:[]});}return {schema_version:1,sources:[...refs.values()],registration_template:{source_id:'project-source-id',source_title:'Required',work:null,edition:null,publisher:null,url:null,project_reference:'project PDF or approved material reference',rights_status:'REVIEW_REQUIRED',rights_reference:null,review_state:'REGISTERED',reviewer:null,reviewed_at:null,evidence:[{candidate_id:'canonical id',page:null,section:null,verse_or_mantra_id:null,field_supported:'text',exact_evidence:'Candidate extraction only until human approval',review_state:'EXTRACTION_CANDIDATE',reviewer:null,reviewed_at:null}]}};}
function main(){const rows=JSON.parse(fs.readFileSync(path.join(ROOT,'m3/canonical_candidates.json'),'utf8')).items,result=build(rows);fs.mkdirSync(OUT,{recursive:true});const write=(name,value)=>fs.writeFileSync(path.join(OUT,name),JSON.stringify(value,null,2)+'\n');write('canonical_catalog.json',{schema_version:1,items:result.items});write('source_registry.json',sourceRegistry(rows));write('review_queue.json',{items:result.items.filter(x=>x.publication_eligibility==='BLOCKED').map(x=>({canonical_id:x.canonical_id,review_status:x.review_status,blockers:x.publication_blockers}))});write('publication_ready.json',{items:result.items.filter(x=>x.publication_eligibility==='READY')});write('publication_blockers.json',{items:result.items.filter(x=>x.publication_eligibility==='BLOCKED').map(x=>({canonical_id:x.canonical_id,blockers:x.publication_blockers}))});write('catalog_summary.json',{...result.summary,duplicate_relationships:result.duplicates,alias_conflict_records:result.aliasConflicts,generated_at:'2026-10-03',production_modified:false});console.log(JSON.stringify(result.summary,null,2));}
if(require.main===module)main();module.exports={LONG_FORM,JAPA_TYPES,key,truthfulType,candidate,build,sourceRegistry};
