#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path');
const {corePublicationIssues,fieldPublicationState}=require('./mantra_publication');
const {sacredTextFindings}=require('./mantra_quality');
const {candidate}=require('./build_mantra_m5_catalog');
const ROOT=path.resolve(__dirname,'../data/mantra'),OUT=path.join(ROOT,'m5_1');
const RESEARCH={
  asato_ma:[{source_id:'brihadaranyaka-1-3-28-ignca',source_title:'The Bṛhadāraṇyaka Upaniṣad with commentary',work:'Bṛhadāraṇyaka Upaniṣad',edition_publisher:'IGNCA digitized edition',section:'1.3.28',url:'https://ignca.gov.in/Asi_data/8283.pdf',field_supported:'text',match_state:'PARTIAL_MATCH_REVIEW_REQUIRED',rights_status:'REVIEW_REQUIRED',rights_reference:null,note:'The three core lines are attested. The production record additionally includes Om and a threefold shanti ending, which this passage does not establish.'}],
  gayatri:[{source_id:'rigveda-3-62-10-wikisource',source_title:'Ṛgveda Sūkta 3.62',work:'Ṛgveda',edition_publisher:'Sanskrit Wikisource transcription',section:'3.62.10',url:'https://sa.wikisource.org/wiki/ऋग्वेदः_सूक्तं_३.६२',field_supported:'text',match_state:'PARTIAL_MATCH_REVIEW_REQUIRED',rights_status:'LICENSED',rights_reference:'Wikisource copyright policy: public domain or CC BY-SA; page-specific attribution and license review required',note:'The Savitṛ verse is present; production also prefixes Om and the vyāhṛtis. Vedic accents and orthography require expert review.'}],
  mahamrityunjaya:[{source_id:'rigveda-7-59-12-witness',source_title:'Ṛgveda 7.59.12',work:'Ṛgveda',edition_publisher:'Vedic verse witness',section:'7.59.12',url:'https://vedapath.app/en/rig-veda/mandala-7/59/12',field_supported:'text',match_state:'PARTIAL_MATCH_REVIEW_REQUIRED',rights_status:'REVIEW_REQUIRED',rights_reference:null,note:'The core verse matches in normalized form; production adds Om and omits Vedic accents. Edition and reuse terms need confirmation.'}],
  hare_krishna:[{source_id:'kali-santarana-ignca-index',source_title:'Kali-santaraṇa Upaniṣad',work:'Kali-santaraṇa Upaniṣad',edition_publisher:'Gaudiya Grantha Mandira indexed by IGNCA',section:null,url:'https://ignca.gov.in/online-digital-resources/gaudiya-grantha-mandira-sanskrit-text-repository/',field_supported:'text',match_state:'VARIANT_REVIEW_REQUIRED',rights_status:'REVIEW_REQUIRED',rights_reference:null,note:'The work is an authoritative lead, but mantra order and edition must be checked against the PDF; no text or rights approval is inferred from the index.'}]
};
function audit(row){const base=candidate(row),evidence=RESEARCH[row.id]||[],textQuality=sacredTextFindings(row.sanskrit_text),trans=fieldPublicationState({...row,transliteration:row.transliteration_iast||row.transliteration_simple||row.transliteration},'transliteration'),meaning=fieldPublicationState(row,'meaning');
  const launch={...base,canonical_id:row.id,source_evidence:evidence,text_quality_findings:textQuality,canonical_identity_verification:'REVIEW_REQUIRED',classification_verification:'REVIEW_REQUIRED',text_verification:'REVIEW_REQUIRED',rights_status:'REVIEW_REQUIRED',rights_reference:null,transliteration_state:trans.displayable?'VERIFIED':trans.present?'WITHHELD_PENDING_REVIEW':'ABSENT',meaning_state:meaning.displayable?'VERIFIED':meaning.present?'WITHHELD_PENDING_REVIEW':'ABSENT',display_fields:{sanskrit:true,transliteration:trans.displayable,meaning:meaning.displayable,practice:false,pronunciation:false,audio:false}};
  const coreInput={...row,canonical_name:row.canonical_name||row.title,content_type:row.mantra_content_type||row.content_type,publication_status:'REVIEW_REQUIRED',text_verification:'REVIEW_REQUIRED',text_sources:[],rights_status:'REVIEW_REQUIRED',rights_reference:null};
  launch.core_publication_blockers=[...new Set([...corePublicationIssues(coreInput),'CANONICAL_IDENTITY_REVIEW_REQUIRED','CLASSIFICATION_REVIEW_REQUIRED',...(textQuality.length?['SACRED_TEXT_QUALITY_REVIEW_REQUIRED']:[]),...(evidence.length?['SOURCE_MATCH_HUMAN_REVIEW_REQUIRED']:['AUTHORITATIVE_TEXT_SOURCE_REQUIRED'])])];launch.core_launch_eligibility=launch.core_publication_blockers.length?'BLOCKED':'READY';return launch;}
function build(rows){const items=rows.map(audit),ready=items.filter(x=>x.core_launch_eligibility==='READY');return {items,ready,summary:{existing_records_audited:items.length,source_matched_exact:items.filter(x=>x.source_evidence.some(e=>e.match_state==='EXACT_MATCH')).length,source_leads_registered:items.filter(x=>x.source_evidence.length).length,text_review_ready:items.filter(x=>x.source_evidence.length&&!x.text_quality_findings.length).length,rights_cleared:items.filter(x=>['PUBLIC_DOMAIN','LICENSED','PROJECT_OWNED','PERMISSION_GRANTED'].includes(x.rights_status)&&x.rights_reference).length,transliteration_ready:items.filter(x=>x.transliteration_state==='VERIFIED').length,meaning_ready:items.filter(x=>x.meaning_state==='VERIFIED').length,core_launch_ready:ready.length,japa_ready:ready.filter(x=>x.japa_eligibility==='ELIGIBLE_BY_CONTENT_TYPE').length,text_only_launch_ready:ready.filter(x=>!x.display_fields.transliteration&&!x.display_fields.meaning).length,human_sanskrit_review_required:items.filter(x=>x.text_verification!=='VERIFIED').length,rights_work_required:items.filter(x=>x.rights_status==='REVIEW_REQUIRED').length,withheld_records:items.filter(x=>x.transliteration_state.startsWith('WITHHELD')||x.meaning_state.startsWith('WITHHELD')).length,blocked:items.length-ready.length}};}
function main(){const rows=JSON.parse(fs.readFileSync(path.join(ROOT,'m3/production_snapshot.json'),'utf8')).items,result=build(rows);fs.mkdirSync(OUT,{recursive:true});const write=(name,value)=>fs.writeFileSync(path.join(OUT,name),JSON.stringify(value,null,2)+'\n');write('launch_candidates.json',{schema_version:1,items:result.items});write('source_evidence.json',{schema_version:1,records:Object.entries(RESEARCH).flatMap(([canonical_id,sources])=>sources.map(source=>({canonical_id,...source})))});write('launch_ready.json',{items:result.ready});write('launch_blockers.json',{items:result.items.map(x=>({canonical_id:x.canonical_id,blockers:x.core_publication_blockers}))});write('launch_summary.json',{...result.summary,generated_at:'2026-10-03',production_modified:false});console.log(JSON.stringify(result.summary,null,2));}
if(require.main===module)main();module.exports={RESEARCH,audit,build};
