#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path');
const {sacredTextFindings}=require('./mantra_quality');
const {candidate}=require('./build_mantra_m5_catalog');
const {RESEARCH:BASE}=require('./build_mantra_m5_1_launch');
const ROOT=path.resolve(__dirname,'../data/mantra'),OUT=path.join(ROOT,'mc_1a');
const EXTRA={
  om_namo_bhagavate:[{source_id:'bhagavata-4-8-54',source_title:'Śrīmad-Bhāgavatam',work:'Bhāgavata Purāṇa',location:'4.8.54',url:'https://vedabase.cc/hi/sb/4/8/54/',rights_status:'REVIEW_REQUIRED',match_state:'STRONG_EXACT_TEXT_MATCH',source_text:'ॐ नमो भगवते वासुदेवाय',note:'The mantra is printed at the opening of verse 4.8.54. Modern translation and editorial material are excluded.'}],
  om_namo_narayanaya:[{source_id:'narayana-upanishad-3',source_title:'Nārāyaṇa Upaniṣad',work:'Nārāyaṇa Upaniṣad',location:'3',url:'https://vedapath.app/en/upanishads/narayana/3',rights_status:'REVIEW_REQUIRED',match_state:'STRONG_EXACT_TEXT_MATCH',source_text:'ॐ नमो नारायणाय',note:'The passage constructs and states the eight-syllable formula. Reuse terms still require review.'}],
  om_namah_shivay:[{source_id:'taittiriya-samhita-4-5-8-1',source_title:'Śrī Rudram, Namakam',work:'Taittirīya Saṃhitā',location:'4.5.8.1',url:null,project_reference:'Primary passage lead: namaḥ śivāya ca śivatarāya ca',rights_status:'REVIEW_REQUIRED',match_state:'PARTIAL_PASSAGE_MATCH',source_text:'नमः शिवाय च शिवतराय च',note:'Production prefixes Om and extracts a segment from the longer Vedic formula.'}],
  shiva_panchakshara:[{source_id:'taittiriya-samhita-4-5-8-1',source_title:'Śrī Rudram, Namakam',work:'Taittirīya Saṃhitā',location:'4.5.8.1',url:null,project_reference:'Primary passage lead: namaḥ śivāya ca śivatarāya ca',rights_status:'REVIEW_REQUIRED',match_state:'PARTIAL_PASSAGE_MATCH',source_text:'नमः शिवाय च शिवतराय च',note:'Production contains the five-syllable segment without the rest of the source formula.'}],
  aditya_hridaya_seed:[{source_id:'msrvvp-vedic-sanskar-textbook',source_title:'Vedic Sanskar Kanishtha Sahayak',work:'Institutional ritual textbook',location:'Surya invocations',url:'https://msrvvp.ac.in/skill_course/textbook/Vedic_Sanskar_Kanishtha_Sahayak_27_06_24.pdf',rights_status:'REVIEW_REQUIRED',match_state:'STRONG_EXACT_TEXT_MATCH',source_text:'ॐ आदित्याय नमः',note:'Institutional witness contains the exact short salutation; it does not establish the current title “Aditya Hridaya Seed”.'}],
  surya_moola:[{source_id:'msrvvp-vedic-sanskar-textbook',source_title:'Vedic Sanskar Kanishtha Sahayak',work:'Institutional ritual textbook',location:'Surya invocations',url:'https://msrvvp.ac.in/skill_course/textbook/Vedic_Sanskar_Kanishtha_Sahayak_27_06_24.pdf',rights_status:'REVIEW_REQUIRED',match_state:'TEXTUAL_VARIANT',source_text:'ॐ ह्रीं घृणि सूर्य आदित्य श्री ॐ',note:'The institutional witness gives a different Surya formula; it does not verify the production text.'}],
  vishnu_sahasranama_seed:[{source_id:'narayana-purvatapiniya-3',source_title:'Nārāyaṇapūrvatāpinīya Upaniṣad',work:'Nārāyaṇapūrvatāpinīya Upaniṣad',location:'third section',url:'https://sanskritdocuments.org/doc_upanishhat/nArAyaNapUrvatApinIyopaniShat.html',rights_status:'REVIEW_REQUIRED',match_state:'DISCOVERY_ONLY',source_text:'ॐ नमो विष्णव',note:'The located reading differs grammatically from production ॐ विष्णवे नमः and SanskritDocuments reuse permission remains unresolved.'}]
};
const SOURCES={...BASE,...EXTRA};
function normalize(v){return String(v||'').normalize('NFC').replace(/[।॥.,\s]/gu,'');}
function differences(text,evidence){if(!evidence)return['NO_SOURCE_TEXT_FOR_COMPARISON'];if(normalize(text)===normalize(evidence.source_text))return ['PUNCTUATION_OR_SPACING_ONLY_IF_ANY'];const out=[];if(/^ॐ/u.test(text)&&!/^ॐ/u.test(evidence.source_text||''))out.push('PRODUCTION_OM_PREFIX');if(!/^ॐ/u.test(text)&&/^ॐ/u.test(evidence.source_text||''))out.push('SOURCE_OM_PREFIX');if((evidence.match_state||'').includes('PARTIAL'))out.push('PRODUCTION_EXTRACTS_SOURCE_PASSAGE');if(evidence.match_state==='TEXTUAL_VARIANT')out.push('FORMULA_OR_ORTHOGRAPHIC_VARIANT');if(evidence.note?.match(/threefold|vyāhṛti|accents|ordering|closing/i))out.push('PREFIX_SUFFIX_ACCENT_OR_ORDER_REVIEW');return out.length?out:['TEXT_DIFFERS_HUMAN_COLLATION_REQUIRED'];}
function record(row){const base=candidate({...row,content_type:row.mantra_content_type||row.content_type||'MANTRA'}),evidence=SOURCES[row.id]||[],primary=evidence[0]||null,diffs=differences(row.sanskrit_text,primary);return {record_id:row.id,current_title:row.canonical_name||row.title,canonical_title_candidate:row.canonical_name||row.title,aliases:row.alternate_names||[],deity_form:(row.deity_ids||[])[0]||row.deity||'Unspecified',current_content_type:row.mantra_content_type||row.content_type||'MANTRA',proposed_content_type:base.content_type,classification_state:'HUMAN_REVIEW_REQUIRED',current_sanskrit:row.sanskrit_text,text_quality:sacredTextFindings(row.sanskrit_text),transliteration:row.transliteration_iast||row.transliteration_simple||row.transliteration||null,transliteration_state:'GENERATED_OR_LEGACY_HUMAN_REVIEW_REQUIRED',meaning:row.meanings||{en:row.meaning_en||null,hi:row.meaning_hi||null},meaning_state:'WITHHELD_PENDING_EVIDENCE',japa_eligibility:base.japa_eligibility,practice_level:row.practice_level||'GENERAL_DEVOTIONAL',restrictions:{requires_guru_guidance:row.requires_guru_guidance??null,requires_initiation:row.requires_initiation??null,evidence_state:'REVIEW_REQUIRED'},primary_source_identity:primary?{work:primary.work,location:primary.location||primary.section||null}:null,source_evidence:evidence,text_comparison:{status:primary?.match_state||'NO_ACCEPTABLE_SOURCE_FOUND',source_text:primary?.source_text||null,differences:diffs,textual_variants:primary?.note||null,production_additions:diffs.filter(x=>/PRODUCTION|PREFIX_SUFFIX/.test(x))},rights:{underlying_ancient_text:primary?'LIKELY_PUBLIC_DOMAIN_HUMAN_CONFIRMATION_REQUIRED':'UNRESOLVED',modern_edition:primary?.rights_status||'UNRESOLVED',transliteration:'UNRESOLVED',translation_meaning:'UNRESOLVED',practice_commentary:'UNRESOLVED',audio:'UNRESOLVED',rights_reference:primary?.rights_reference||null},review_requirements:{sanskrit:'HUMAN_REVIEW_REQUIRED',transliteration:'HUMAN_REVIEW_REQUIRED',meaning:'HUMAN_REVIEW_REQUIRED_OR_WITHHOLD',classification:'HUMAN_REVIEW_REQUIRED',rights:'HUMAN_DECISION_REQUIRED'},publication_blockers:['TEXT_REVIEW_REQUIRED','CLASSIFICATION_REVIEW_REQUIRED','RIGHTS_CLEARANCE_REQUIRED','REVIEW_ATTRIBUTION_REQUIRED','PUBLICATION_APPROVAL_REQUIRED',...(primary?['SOURCE_COLLATION_REQUIRED']:['AUTHORITATIVE_TEXT_SOURCE_REQUIRED'])]};}
function build(rows){const records=rows.map(record),evidence=records.flatMap(r=>r.source_evidence.map(s=>({record_id:r.record_id,...s}))),comparisons=records.map(r=>({record_id:r.record_id,current_dharmasetu_text:r.current_sanskrit,source_text:r.text_comparison.source_text,status:r.text_comparison.status,differences:r.text_comparison.differences,source_location:r.primary_source_identity})),rights=records.map(r=>({record_id:r.record_id,...r.rights})),queue=records.map(r=>({record_id:r.record_id,current_dharmasetu_text:r.current_sanskrit,source_text_or_evidence:r.text_comparison.source_text,source_location:r.primary_source_identity,source_urls:r.source_evidence.map(s=>s.url).filter(Boolean),differences:r.text_comparison.differences,rights_status:r.rights,proposed_classification:r.proposed_content_type,japa_eligibility:r.japa_eligibility,decisions_required:['Confirm canonical identity and title','Collate Sanskrit against selected edition','Accept or reject textual variant/additions','Approve content classification and Japa eligibility','Record reusable rights basis','Review transliteration or withhold','Review meaning and rights or withhold']}));const count=p=>records.filter(p).length;return {records,evidence,comparisons,rights,queue,summary:{records_audited:records.length,strong_exact_source_matches:count(r=>r.text_comparison.status==='STRONG_EXACT_TEXT_MATCH'),partial_source_matches:count(r=>['PARTIAL_MATCH_REVIEW_REQUIRED','PARTIAL_PASSAGE_MATCH','TEXTUAL_VARIANT','VARIANT_REVIEW_REQUIRED'].includes(r.text_comparison.status)),discovery_only_source_leads:count(r=>r.text_comparison.status==='DISCOVERY_ONLY'),records_lacking_source:count(r=>r.text_comparison.status==='NO_ACCEPTABLE_SOURCE_FOUND'),records_with_textual_variants:count(r=>!['STRONG_EXACT_TEXT_MATCH','NO_ACCEPTABLE_SOURCE_FOUND','DISCOVERY_ONLY'].includes(r.text_comparison.status)),rights_clear_candidates:0,rights_decision_required:records.length,proposed_japa_eligible:count(r=>r.japa_eligibility==='ELIGIBLE_BY_CONTENT_TYPE'),proposed_non_japa:count(r=>r.japa_eligibility!=='ELIGIBLE_BY_CONTENT_TYPE'),transliteration_review_ready:count(r=>!!r.transliteration),meaning_review_ready:count(r=>Object.values(r.meaning||{}).some(Boolean)),human_sanskrit_review_queue:queue.length}};}
function main(){const rows=JSON.parse(fs.readFileSync(path.join(ROOT,'m3/production_snapshot.json'),'utf8')).items,result=build(rows);fs.mkdirSync(OUT,{recursive:true});const write=(n,v)=>fs.writeFileSync(path.join(OUT,n),JSON.stringify(v,null,2)+'\n');write('records.json',{items:result.records});write('source_evidence.json',{items:result.evidence});write('text_comparisons.json',{items:result.comparisons});write('rights_review.json',{items:result.rights});write('human_review_queue.json',{items:result.queue});write('summary.json',{...result.summary,generated_at:'2026-10-03',production_modified:false});console.log(JSON.stringify(result.summary,null,2));}
if(require.main===module)main();module.exports={SOURCES,normalize,differences,record,build};
